name: Build and Deploy GitBook Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '12'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Fix graceful-fs compatibility
      run: |
        npm install -g graceful-fs@4.2.10
        
    - name: Install GitBook CLI with compatibility fixes
      run: |
        npm install -g gitbook-cli@2.3.2
        # Apply graceful-fs patch
        cd $(npm root -g)/gitbook-cli/node_modules/npm/node_modules/
        if [ -d "graceful-fs" ]; then
          npm install graceful-fs@4.2.10 --no-save
        fi
        gitbook fetch 3.2.3
      
    - name: Ensure docs directory exists
      run: |
        mkdir -p docs
        if [ ! -f "docs/README.md" ]; then
          echo "# openRPG Documentation" > docs/README.md
          echo "Documentação do openRPG Backend" >> docs/README.md
        fi
        if [ ! -f "docs/SUMMARY.md" ]; then
          echo "# Summary" > docs/SUMMARY.md
          echo "* [Introduction](README.md)" >> docs/SUMMARY.md
        fi
      
    - name: Install GitBook plugins
      run: |
        cd docs
        gitbook install || echo "Plugin installation failed, continuing..."
      
    - name: Build GitBook
      run: |
        gitbook build docs _book
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
        publish_branch: gh-pages
        
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gitbook-build
        path: _book/
        retention-days: 7
