name: Build and Deploy GitBook Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '12'
        
    - name: Install dependencies
      run: |
        # Remove package-lock.json para evitar conflitos de versão
        rm -f package-lock.json
        npm install
      
    - name: Fix graceful-fs compatibility
      run: |
        npm install -g graceful-fs@4.2.10
        
    - name: Install GitBook CLI with compatibility fixes
      run: |
        npm install -g gitbook-cli@2.3.2
        # Apply graceful-fs patch
        cd $(npm root -g)/gitbook-cli/node_modules/npm/node_modules/
        if [ -d "graceful-fs" ]; then
          npm install graceful-fs@4.2.10 --no-save
        fi
        gitbook fetch 3.2.3
      
    - name: Ensure docs directory exists
      run: |
        mkdir -p docs
        if [ ! -f "docs/README.md" ]; then
          echo "# openRPG Documentation" > docs/README.md
          echo "Documentação do openRPG Backend" >> docs/README.md
        fi
        if [ ! -f "docs/SUMMARY.md" ]; then
          echo "# Summary" > docs/SUMMARY.md
          echo "* [Introduction](README.md)" >> docs/SUMMARY.md
        fi
      
    - name: Install GitBook plugins
      run: |
        cd docs
        gitbook install || echo "Plugin installation failed, continuing..."
      
    - name: Build GitBook
      run: |
        echo "Building GitBook..."
        gitbook build docs _book
        echo "Build completed. Checking output..."
        ls -la _book/ || echo "No _book directory found"
        
    - name: Verify build output
      run: |
        if [ ! -d "_book" ]; then
          echo "Error: _book directory not created"
          exit 1
        fi
        if [ ! -f "_book/index.html" ]; then
          echo "Error: index.html not found in _book"
          exit 1
        fi
        echo "Build verification successful"
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./_book
        publish_branch: gh-pages
        force_orphan: true
        
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gitbook-build
        path: _book/
        retention-days: 7
